export const CLOTHES_COLORS = [
  '#FFD947',
  '#DAB0FF',
  '#FEA99A',
  '#A2C7FF',
  '#458FFF',
  '#4B5FFA',
  '#17294C',
];

export const BEARD_IDS = ['NO_BEARD', 'TWO_DAY_BEARD', 'LONG_BEARD'];

export const CLOTHES_IDS = [
  'CARDIGAN',
  'FLOWERY_TEE',
  'JACKET',
  'OVERSHIRT',
  'POCKET_TEE',
  'STRIPED_JERSEY',
  'SWEATER',
  'TANK_TOP',
  'TEE',
];

export const HAIR_COLORS = ['#FFD947', '#F0C014', '#C26604', '#17294D'];

export const HAIRCUT_IDS = [
  'BOB_CUT_WITH_BANGS',
  'CURLY',
  'LONG_AND_WAVY',
  'LONG_AND_STRAIGHT',
  'BOB_CUT',
  'BUN',
  'PONYTAIL',
  'LONG_AND_VOLUMINOUS',
  'SHORT_BOB_CUT',
  'VOLUMINOUS',
  'CURLY_AND_VOLUMINOUS',
  'NATURAL',
  'SHORT_AND_FLAT',
  'SHORT_AND_VOLUMINOUS',
  'VERY_SHORT_AND_FLAT',
  'WAVY_AND_VOLUMINOUS',
];

export const SKIN_COLORS = ['#FFE9D0', '#F7D2A7', '#C26604'];
